services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: aryak
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: testdb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./kerberos/pg.keytab:/var/lib/postgresql/pg.keytab:ro
      - ./postgres-config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgres-config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - postgres_net

volumes:
  postgres_data:

networks:
  postgres_net:
    driver: bridge