spring:
  application:
    name: spring-kerberos
  datasource:
    url: jdbc:postgresql://localhost:5435/testdb
    username: aryak
    password: root@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

